apiVersion: v1
kind: ConfigMap

metadata:
  name: streamingapp-config
  namespace: {{ .Values.namespace }}

data:
  MONGO_HOST: mongodb
  MONGO_PORT: "{{ .Values.mongodb.port }}"
  MONGO_DB: "{{ .Values.mongodb.database }}"

  AUTH_SERVICE_URL: http://auth-service:3001
  STREAMING_SERVICE_URL: http://streaming-service:3002
  ADMIN_SERVICE_URL: http://admin-service:3003
  CHAT_SERVICE_URL: http://chat-service:3004